version: 2
updates:

# Fetch and update latest `npm` packages
- package-ecosystem: npm
  directory: '/'
  schedule:
    interval: daily
    time: '00:00'
  open-pull-requests-limit: 10
  reviewers:
    - MatteoH2O1999
  assignees:
    - MatteoH2O1999
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
  ignore:
    - dependency-name: vue
      versions: ['>=3.0.0']
    - dependency-name: nuxt
      versions: ['>=3.0.0']
    - dependency-name: '@fortawesome/vue-fontawesome'
      versions: ['>=3.0.0']
    - dependency-name: '@nuxt/content'
      versions: ['>=2.0.0']
    - dependency-name: '@nuxt/image'
      versions: ['>=1.0.0']
    - dependency-name: '@nuxtjs/i18n'
      versions: ['>=8.0.0']
    - dependency-name: webpack
      versions: ['>=5.0.0']
    - dependency-name: remark-math
      versions: ['>=5.0.0']
    - dependency-name: rehype-mathjax
      versions: ['>=4.0.0']
  groups:
    nuxtjs:
      patterns:
        - "@nuxt/*"
        - "@nuxtjs/*"
        - "nuxt"
    vue:
      patterns:
        - "vue*"
    font-awesome:
      patterns:
        - "@fortawesome/*"

# Fetch and update latest `github-actions` pkgs
- package-ecosystem: github-actions
  directory: '/'
  schedule:
    interval: daily
    time: '00:00'
  open-pull-requests-limit: 10
  reviewers:
    - MatteoH2O1999
  assignees:
    - MatteoH2O1999
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
