name: Deploy website to Pages

on:
  push:
    branches:
      - "main"

permissions:
  contents: read

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  NODE_VERSION: 20

jobs:
  # Test website content
  test:
    name: Test website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false
          submodules: "recursive"
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
      - name: Install production and development dependencies
        run: npm ci
      - name: Run tests
        run: npm run test-ci
        env:
          FORCE_COLOR: 3

  # Build website and upload artifact
  build:
    name: Build website
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout website repository
        uses: actions/checkout@v5
        with:
          persist-credentials: false
          submodules: recursive
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
      - name: Install production dependencies
        run: npm ci --omit=dev
      - name: Build with Nuxt
        run: npm run generate
      - name: Upload website artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: dist/

  # Deploy site to pages
  deploy:
    permissions:
      pages: write
      id-token: write
    name: Deploy pages
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4
