name: Deploy website to Pages

on:
  push:
    branches:
      - "main"

permissions:
  contents: read

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  NODE_VERSION: 16

jobs:
  test:
    name: Test website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - name: Install production and development dependencies
        run: npm ci --include=dev
      - name: Generate dist folder
        run: npm run generate
      - name: Run tests
        run: npm run test

  # Build website and upload artifact
  build:
    name: Build website
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout website repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - name: Install production dependencies
        run: npm ci --omit=dev
      - name: Build with Nuxt
        run: npm run generate
      - name: Upload website artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: dist/

  # Check build status and deploy
  report-build-status:
    permissions:
      pages: write
      id-token: write
    name: Report pages build status
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Github Pages
        uses: actions/deploy-pages@v1
        with:
          emit_telemetry: true

  deploy:
    permissions:
      pages: write
      id-token: write
    name: Deploy pages
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v1
