name: Check pull request

on:
  pull_request:

permissions:
  pull-requests: write
  contents: read

env:
  PR_AUTHOR: ${{ github.event.pull_request.user.login }}
  NODE_VERSION: 18

jobs:
  test:
    name: Test website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - name: Install production and development dependencies
        run: npm ci --include=dev
      - name: Run tests
        run: npm run test-ci
        env:
          FORCE_COLOR: 3

  build:
    name: Test build website
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - name: Install production dependencies
        run: npm ci --omit=dev
      - name: Test build with Nuxt
        run: npm run generate

  clean:
    name: Clean contribution if not authorized
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Detect pull request author
        run: echo "Pull request author is $PR_AUTHOR"
      - name: Clean contribution
        if: ${{ env.PR_AUTHOR != 'MatteoH2O1999' && env.PR_AUTHOR != 'dependabot[bot]' }}
        uses: dessant/repo-lockdown@v3
        with:
          pr-comment: This repository is a personal website and as such it does not accept pull requests.
          log-output: true

